# using this extension on vscode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client


@baseUrl = http://localhost:3333/user

### 1st GET ALL
# @name users
GET {{baseUrl}}

### 2nd GET BY FIRST USER ID
@firstUserId = {{users.response.body.data[0].id}}
GET {{baseUrl}}/{{firstUserId}}

### 3rd POST
POST {{baseUrl}}/new
Content-Type: application/json

{
  "name": "Tarantini2"
}
